language: cpp

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
     - llvm-toolchain-trusty
    packages:
     - llvm-dev
     - libclang-dev
     - clang

before_install:
 # Install a supported cmake version (>= 3.4.3)
 - wget -O cmake.sh https://cmake.org/files/v3.11/cmake-3.11.2-Linux-x86_64.sh
 - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local

 # Extract the version number from the most-recently installed LLVM
 - VERSION=`ls -t /usr/lib/ | grep '^llvm-' | head -n 1 | sed -E 's/llvm-(.+)/\1/'`

 # Absolute paths to LLVM's root and bin directory
 - ROOT_PATH=`llvm-config-$VERSION --prefix`
 - BIN_PATH=`llvm-config-$VERSION --bindir`

script:
# Build IWYU
 - mkdir build
 - cd build
 - cmake ..
 - make
 - ctest