#language: cpp
sudo: false
notifications:
  email: false

os: linux
dist: trusty


matrix:
  include:
    # clang on macOS
  - env: CXX=clang++-6.0
    os: osx
    compiler: clang
    osx_image: xcode8.3

  - env: CXX=clang++-6.0
    os: osx
    compiler: clang
    osx_image: xcode9.4

  - env: CXX=clang++-6.0
    addons:
      apt:
        update: true
        packages:
        - clang-6.0
        - libopenblas-dev
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-trusty-6.0

  - env: CXX=g++-8
    addons:
    apt:
      update: true
      packages:
      - g++-8.0
      - libopenblas-dev
      sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0


install:
- DEPS_DIR="${HOME}/deps"
- mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    CMAKE_URL="https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.tar.gz"
    mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  else
    brew install cmake || brew upgrade cmake
  fi
- cmake --version


script:
 - cd ${TRAVIS_BUILD_DIR}
 - mkdir build
 - cd build
 - cmake ..
 - make
 - ctest --verbose