Athena: athena::backend::AbstractMemoryManager Class Reference
athena::backend::AbstractMemoryManager Class Reference abstract
#include <AbstractMemoryManager.h>
Public Member Functions
virtual void init ()=0
virtual void deinit ()=0
void resetTable ()
void addTensor (athena::core::Tensor *tensor)
virtual void * getPhysicalAddress (vm_word virtualAddress)=0
void loadAndLock (athena::core::Tensor *tensor)
void loadAndLock (vm_word address)
virtual void loadAndLock (vm_word address, unsigned long length)=0
virtual void unlock (vm_word address)=0
virtual void deleteFromMem (vm_word address)=0
athena::core::Tensor * getTensor (vm_word address)
void allocateAndLock (athena::core::Tensor *tensor)
void allocateAndLock (vm_word address)
virtual void allocateAndLock (vm_word address, unsigned long length)=0
virtual void setData (vm_word tensorAddress, vm_word offset, vm_word length, void *data)=0
virtual void getData (vm_word tensorAddress, vm_word offset, vm_word length, void *data)=0
Protected Attributes
std::list< athena::core::Tensor *> tensors
Detailed Description
This class is an interface for physical memory managers. They provide conversion between virtual addresses and physical ones. A typical strategy for memory manager is to allocate as much memory as possible and then provide tensors with it. This class also encapsulates table of athena::core::Tensor objects. One can think of it as of variables table in a compiler.
Definition at line 30 of file AbstractMemoryManager.h.
Member Function Documentation
addTensor()
void athena::backend::AbstractMemoryManager::addTensor (athena::core::Tensor * tensor)
Adds Tensor to table
Parameters
tensor Tensor, that will be added
Definition at line 20 of file AbstractMemoryManager.cpp.
allocateAndLock() [1/3]
void athena::backend::AbstractMemoryManager::allocateAndLock (athena::core::Tensor * tensor)
Allocate space in the fastest memory available without loading any data and lock it (prevent from being offloaded)
Parameters
tensor Tensor memory is being allocated for
Definition at line 54 of file AbstractMemoryManager.cpp.
Referenced by athena::core::initializers::DataInitializer::initialize().
allocateAndLock() [2/3]
void athena::backend::AbstractMemoryManager::allocateAndLock (vm_word address)
Allocate space in the fastest memory available without loading any data and lock it (prevent from being offloaded)
Parameters
address Virtual address of Tensor memory is being allocated for
Definition at line 60 of file AbstractMemoryManager.cpp.
allocateAndLock() [3/3]
virtual void athena::backend::AbstractMemoryManager::allocateAndLock (vm_word address, unsigned long length) pure virtual
Allocate space in the fastest memory available without loading any data and lock it (prevent from being offloaded)
Parameters
address Virtual address of Tensor memory is being allocated for
length Length in bytes for the piece of memory that is being allocated
Implemented in athena::backend::generic::GenericMemoryManager.
deleteFromMem()
virtual void athena::backend::AbstractMemoryManager::deleteFromMem (vm_word address) pure virtual
Mark corresponding memory chunk as free
Parameters
address Virtual address
Implemented in athena::backend::generic::GenericMemoryManager.
getPhysicalAddress()
virtual void* athena::backend::AbstractMemoryManager::getPhysicalAddress (vm_word virtualAddress) pure virtual
Convert virtual address to physical one
Parameters
virtualAddress Virtual address, unsigned long from 0 to 2^64-1
Returns
Pointer to physical memory
Implemented in athena::backend::generic::GenericMemoryManager.
loadAndLock() [1/3]
void athena::backend::AbstractMemoryManager::loadAndLock (athena::core::Tensor * tensor)
Move data to the fastest memory type available (e.g. from hard drive to RAM) and lock it (prevent from being offloaded)
Parameters
tensor Tensor containing data
Definition at line 25 of file AbstractMemoryManager.cpp.
loadAndLock() [2/3]
void athena::backend::AbstractMemoryManager::loadAndLock (vm_word address)
Move data to the fastest memory type available (e.g. from hard drive to RAM) and lock it (prevent from being offloaded)
Parameters
address Virtual address of Tensor containing data
Definition at line 30 of file AbstractMemoryManager.cpp.
loadAndLock() [3/3]
virtual void athena::backend::AbstractMemoryManager::loadAndLock (vm_word address, unsigned long length) pure virtual
Move data to the fastest memory type available (e.g. from hard drive to RAM) and lock it (prevent from being offloaded)
Parameters
address Virtual address
length Size of Tensor in bytes
Implemented in athena::backend::generic::GenericMemoryManager.
resetTable()
void athena::backend::AbstractMemoryManager::resetTable ()
Clears table of Tensors
Definition at line 16 of file AbstractMemoryManager.cpp.
setData()
virtual void athena::backend::AbstractMemoryManager::setData (vm_word tensorAddress, vm_word offset, vm_word length, void * data) pure virtual
Sets memory with the data
Parameters
tensorAddress Virtual address of Tensor beginning (see Tensor::getStartAddress)
offset Offset in bytes from the beginning
length Length of piece of data in bytes
data Pointer to data
Implemented in athena::backend::generic::GenericMemoryManager.
Referenced by athena::core::initializers::DataInitializer::initialize().
unlock()
virtual void athena::backend::AbstractMemoryManager::unlock (vm_word address) pure virtual
Lets data be offloaded to a slower memory type (e.g. from RAM to HDD)
Parameters
address Virtual address
Implemented in athena::backend::generic::GenericMemoryManager.
Referenced by athena::core::initializers::DataInitializer::initialize().
The documentation for this class was generated from the following files:
backend/AbstractMemoryManager.h
backend/AbstractMemoryManager.cpp