Athena: athena::core::TensorShape Class Reference
athena::core::TensorShape Class Reference
#include <TensorShape.h>
Public Member Functions
TensorShape (std::vector< size_t > shape)
TensorShape (unsigned long *shape, unsigned long length)
TensorShape (const TensorShape &)
TensorShape & operator= (const TensorShape &)
unsigned long dimensions () const
unsigned long dim (unsigned long n) const
unsigned long totalSize () const
const std::vector< unsigned long > & getShape () const
bool operator== (const TensorShape &) const
bool operator!= (const TensorShape &rhs) const
Detailed Description
Class represents size parameters for Tensor
Definition at line 16 of file TensorShape.h.
Member Function Documentation
dim()
unsigned long athena::core::TensorShape::dim (unsigned long n) const
Gives size for certain dimension
Parameters
n Dimension index (0 <= d < dimensions)
Returns
Size of dimension n
Definition at line 24 of file TensorShape.cpp.
Referenced by operator==().
dimensions()
unsigned long athena::core::TensorShape::dimensions () const
Returns
Number of dimensions in Tensor
Definition at line 20 of file TensorShape.cpp.
Referenced by operator==().
operator!=()
bool athena::core::TensorShape::operator!= (const TensorShape & rhs) const
Parameters
rhs TensorShape to be compared with
Returns
True if dimensions are different, else False
Definition at line 49 of file TensorShape.cpp.
operator==()
bool athena::core::TensorShape::operator== (const TensorShape & rhs) const
Returns
True if dimensions are equal, else False
Definition at line 33 of file TensorShape.cpp.
totalSize()
unsigned long athena::core::TensorShape::totalSize () const
Returns
Total number of elements in Tensor
Definition at line 8 of file TensorShape.cpp.
Referenced by athena::backend::VirtualMemory::allocate(), athena::backend::AbstractMemoryManager::allocateAndLock(), and athena::backend::AbstractMemoryManager::loadAndLock().
The documentation for this class was generated from the following files:
core/TensorShape.h
core/TensorShape.cpp